name: Deploy
on:
  pull_request:
    types: [closed]
    branches:
      - main
      - dev

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Deploy Production
      if: github.base_ref == 'main'
      uses: wei/git-sync@v3
      with:
        source_repo: "https://github.com/${{ github.repository }}.git"
        source_branch: "${{ github.base_ref }}"
        destination_repo: ${{ secrets.SPRIKEY_GIT_URL }}
        destination_branch: "master"

    - name: Deploy Development
      if: github.base_ref == 'dev'
      uses: wei/git-sync@v3
      with:
        source_repo: "https://github.com/${{ github.repository }}.git"
        source_branch: "${{ github.base_ref }}"
        destination_repo: ${{ secrets.SPRIKEYDEV_GIT_URL }}
        destination_branch: "master"
