on:
  pull_request:
    types: [closed]
    branches:
      - dev

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Check Branch
      run: echo "${{ github.base_ref }} https://github.com/${{ github.repository }}.git"

    - name: Deploy
      uses: wei/git-sync@v1
      env:
        SOURCE_REPO: "https://github.com/${{ github.repository }}.git"
        SOURCE_BRANCH: "dev"
        DESTINATION_REPO: ${{ secrets.SPRIKEYDEV_GIT_URL }}
        DESTINATION_BRANCH: "master"
      with:
        args: $SOURCE_REPO $SOURCE_BRANCH $DESTINATION_REPO $DESTINATION_BRANCH